### ISSUE TITLE
Unable to find binary when run from external repository

### ISSUE THREAD

**Issue by Anders429** [felixjones/github-mgba-rom-test#2]
When trying to run this action in another repository, it seems the action cannot find `bin/ubuntu/mgba-rom-test`. I get the following error message: 

```
/home/runner/work/_temp/0f45703b-ba62-4f15-bee7-7c8df464fcad.sh: line 2: bin/ubuntu/mgba-rom-test: No such file or directory
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Error: Process completed with exit code 1.
```

The repository I tried to run this action on is here: https://github.com/Anders429/mgba_tests (run [here](https://github.com/Anders429/mgba_tests/actions/runs/8084166381)). I used an action that is nearly identical to the example from this repository, but let me know if anything is missing. Here is one of the job definitions I used:

``` yaml
jobs:
  test-pass:
    runs-on: ubuntu-latest
    name: This test should pass
    steps:
      - uses: actions/checkout@v3
      - id: pass
        uses: felixjones/github-mgba-rom-test@v1
        with:
          swi-call: 0x27
          read-register: 'r0'
          rom-path: 'pass.gba'
          success-code: 0  # Pass
```

I'm not sure if I'm missing something, or if something is misconfigured in the action itself.

**Comment by Anders429** [comment]
Just verified that it does indeed work on `main` after merging #3. Thanks! If you could release a new patch version, that would be helpful, since I currently am just [pinning the commit](https://github.com/Anders429/mgba_tests/blob/bd6b692d16cad2d28e1a4ac79ddf92b3dc0cfef1/.github/workflows/actions.yml#L10). Looks like you can move the `v1` tag, according to [github actions docs](https://docs.github.com/en/actions/creating-actions/about-custom-actions#using-release-management-for-actions).

**Comment by felixjones** [comment]
Republished the v1 tag, could you check that this has worked?

**Comment by Anders429** [comment]
Just checked, it's still not working. I get the same message as I got originally.

Looking at the repository, it seems that the `v1` tag is still at the initial commit: https://github.com/felixjones/github-mgba-rom-test/tree/v1. It looks like you'll need to move the tag itself to a new commit. I'm not entirely sure the best way to do that. Perhaps removing the tag and creating a new one with the same name? [Git Basics - Tagging](https://git-scm.com/book/en/v2/Git-Basics-Tagging) that the github actions docs links to doesn't seem to mention anything about changing the commit an existing tag points to.

**Comment by felixjones** [comment]
Alright, I deleted the v1 tag and recreated it, that should probably fix this

**Comment by Anders429** [comment]
Nice, I can confirm it works. Thanks a ton!
